export const ACHIEVEMENTS = [
  {
    id: "firstGame",
    icon: "⭐",
    category: "beginner",
    title: { el: "Πρώτη Φορά!", en: "First Time!" },
    description: { el: "Ολοκλήρωσε το πρώτο σου παιχνίδι", en: "Complete your first game" },
    condition: (stats) => stats.totalGamesPlayed >= 1,
  },
  {
    id: "fiveGames",
    icon: "🎮",
    category: "champion",
    title: { el: "5 Παιχνίδια!", en: "5 Games!" },
    description: { el: "Ολοκλήρωσε 5 παιχνίδια", en: "Complete 5 games" },
    condition: (stats) => stats.totalGamesPlayed >= 5,
  },
  {
    id: "tenGames",
    icon: "🏅",
    category: "champion",
    title: { el: "10 Παιχνίδια!", en: "10 Games!" },
    description: { el: "Ολοκλήρωσε 10 παιχνίδια", en: "Complete 10 games" },
    condition: (stats) => stats.totalGamesPlayed >= 10,
  },
  {
    id: "twentyFiveGames",
    icon: "🎯",
    category: "champion",
    title: { el: "25 Παιχνίδια!", en: "25 Games!" },
    description: { el: "Ολοκλήρωσε 25 παιχνίδια", en: "Complete 25 games" },
    condition: (stats) => stats.totalGamesPlayed >= 25,
  },
  {
    id: "fiftyGames",
    icon: "👑",
    category: "champion",
    title: { el: "50 Παιχνίδια!", en: "50 Games!" },
    description: { el: "Ολοκλήρωσε 50 παιχνίδια", en: "Complete 50 games" },
    condition: (stats) => stats.totalGamesPlayed >= 50,
  },
  {
    id: "hundredGames",
    icon: "💎",
    category: "champion",
    title: { el: "100 Παιχνίδια!", en: "100 Games!" },
    description: { el: "Ολοκλήρωσε 100 παιχνίδια", en: "Complete 100 games" },
    condition: (stats) => stats.totalGamesPlayed >= 100,
  },
  {
    id: "perfectScore",
    icon: "🏆",
    category: "accuracy",
    title: { el: "Τέλειο Σκορ!", en: "Perfect Score!" },
    description: { el: "Πέτυχε τέλειο σκορ σε ένα παιχνίδι", en: "Get a perfect score in a game" },
    condition: (stats, lastGame) => lastGame && lastGame.total > 0 && lastGame.score === lastGame.total,
  },
  {
    id: "streak3",
    icon: "🔥",
    category: "streak",
    title: { el: "3 Μέρες Σερί!", en: "3 Day Streak!" },
    description: { el: "Παίξε 3 μέρες στη σειρά", en: "Play 3 days in a row" },
    condition: (stats) => stats.streak >= 3,
  },
  {
    id: "streak5",
    icon: "🔥",
    category: "streak",
    title: { el: "5 Μέρες Σερί!", en: "5 Day Streak!" },
    description: { el: "Παίξε 5 μέρες στη σειρά", en: "Play 5 days in a row" },
    condition: (stats) => stats.streak >= 5,
  },
  {
    id: "streak7",
    icon: "🌟",
    category: "streak",
    title: { el: "7 Μέρες Σερί!", en: "7 Day Streak!" },
    description: { el: "Παίξε 7 μέρες στη σειρά", en: "Play 7 days in a row" },
    condition: (stats) => stats.streak >= 7,
  },
  {
    id: "streak14",
    icon: "💪",
    category: "streak",
    title: { el: "2 Εβδομάδες Σερί!", en: "2 Week Streak!" },
    description: { el: "Παίξε 14 μέρες στη σειρά", en: "Play 14 days in a row" },
    condition: (stats) => stats.streak >= 14,
  },
  {
    id: "correct50",
    icon: "📚",
    category: "accuracy",
    title: { el: "50 Σωστά!", en: "50 Correct!" },
    description: { el: "Απάντησε 50 σωστές απαντήσεις", en: "Answer 50 correct answers" },
    condition: (stats) => stats.totalCorrect >= 50,
  },
  {
    id: "correct100",
    icon: "🎓",
    category: "accuracy",
    title: { el: "100 Σωστά!", en: "100 Correct!" },
    description: { el: "Απάντησε 100 σωστές απαντήσεις", en: "Answer 100 correct answers" },
    condition: (stats) => stats.totalCorrect >= 100,
  },
  {
    id: "correct500",
    icon: "🧠",
    category: "accuracy",
    title: { el: "500 Σωστά!", en: "500 Correct!" },
    description: { el: "Απάντησε 500 σωστές απαντήσεις", en: "Answer 500 correct answers" },
    condition: (stats) => stats.totalCorrect >= 500,
  },
  {
    id: "difficultyLevel3",
    icon: "📈",
    category: "champion",
    title: { el: "Επίπεδο 3!", en: "Level 3!" },
    description: { el: "Φτάσε στο επίπεδο δυσκολίας 3", en: "Reach difficulty level 3" },
    condition: (stats) => stats.maxDifficulty >= 3,
  },
  {
    id: "difficultyLevel5",
    icon: "🚀",
    category: "champion",
    title: { el: "Επίπεδο 5!", en: "Level 5!" },
    description: { el: "Φτάσε στο μέγιστο επίπεδο δυσκολίας", en: "Reach max difficulty level" },
    condition: (stats) => stats.maxDifficulty >= 5,
  },
  {
    id: "monthGoal",
    icon: "🏆",
    category: "accuracy",
    title: { el: "Στόχος Μήνα!", en: "Monthly Goal!" },
    description: { el: "Φτάσε τα 100 σωστά σε ένα μήνα", en: "Reach 100 correct in one month" },
    condition: (stats) => stats.monthlyCorrect >= 100,
  },
];

export const ACHIEVEMENT_CATEGORIES = {
  beginner: { el: "Αρχάριος", en: "Beginner", icon: "🌱" },
  streak:   { el: "Σερί", en: "Streak Master", icon: "🔥" },
  accuracy: { el: "Ακρίβεια", en: "Accuracy", icon: "🎯" },
  champion: { el: "Πρωταθλητής", en: "Champion", icon: "👑" },
};
