export const ADULT_GAME_CATEGORIES = [
  {
    id: "brainTraining",
    title: { el: "Εξάσκηση Μυαλού", en: "Brain Training" },
    desc: { el: "Quiz γνώσεων και παιχνίδια μνήμης, αντίδρασης & συγκέντρωσης", en: "Knowledge quizzes and memory, reaction & focus games" },
    icon: "🧠",
    gradient: "from-violet-500 to-purple-600",
    hasQuiz: true,
    subgroups: [
      { label: { el: "🧠 Μνήμη", en: "🧠 Memory" }, ids: ["memoryCards", "rememberSequence", "simon", "memoryPath", "matchSymbols", "missingItem", "colorSequence", "wordMemory", "chunking", "digitSpan"] },
      { label: { el: "👁️ Παρατήρηση & Συγκέντρωση", en: "👁️ Observation & Focus" }, ids: ["findDifference", "visualMemory", "attentionGrid", "patternSpeed", "focusFilter", "stroopTest", "nBack", "mentalRotation"] },
      { label: { el: "⚡ Ταχύτητα & Αντίδραση", en: "⚡ Speed & Reaction" }, ids: ["quickReaction", "speedMath", "numberBonds", "reactionChain"] },
    ],
    games: [
      { id: "memoryCards", title: { el: "Memory Cards", en: "Memory Cards" }, icon: "🃏", desc: { el: "Βρες τα ζευγάρια", en: "Find matching pairs" } },
      { id: "rememberSequence", title: { el: "Θυμήσου τη Σειρά", en: "Remember the Sequence" }, icon: "🔢", desc: { el: "Τοποθέτησε με τη σωστή σειρά", en: "Place in correct order" } },
      { id: "simon", title: { el: "Simon Game", en: "Simon Game" }, icon: "🎨", desc: { el: "Επανάλαβε τη σειρά χρωμάτων", en: "Repeat the color sequence" } },
      { id: "findDifference", title: { el: "Βρες τη Διαφορά", en: "Find the Difference" }, icon: "🔍", desc: { el: "Εντόπισε τις διαφορές", en: "Spot the differences" } },
      { id: "quickReaction", title: { el: "Γρήγορη Αντίδραση", en: "Quick Reaction" }, icon: "⚡", desc: { el: "Πάτα όσο πιο γρήγορα μπορείς", en: "Tap as fast as you can" } },
      { id: "visualMemory", title: { el: "Οπτική Μνήμη", en: "Visual Memory" }, icon: "👁️", desc: { el: "Θυμήσου τα φωτισμένα τετράγωνα", en: "Remember highlighted squares" } },
      { id: "speedMath", title: { el: "Αριθμητική Ταχύτητας", en: "Speed Math" }, icon: "🔢", desc: { el: "Λύσε πράξεις γρήγορα", en: "Solve math quickly" } },
      { id: "memoryPath", title: { el: "Memory Path", en: "Memory Path" }, icon: "🛤️", desc: { el: "Θυμήσου τη διαδρομή", en: "Remember the path" } },
      { id: "matchSymbols", title: { el: "Ταίριαξε τα Σύμβολα", en: "Match Symbols" }, icon: "🔄", desc: { el: "Ταίριαξε σχήματα μνήμης", en: "Match memorized shapes" } },
      { id: "missingItem", title: { el: "Missing Item", en: "Missing Item" }, icon: "❓", desc: { el: "Βρες τι λείπει", en: "Find what's missing" } },
      { id: "stroopTest", title: { el: "Stroop Test", en: "Stroop Test" }, icon: "🎯", desc: { el: "Πάτα το χρώμα, όχι τη λέξη", en: "Tap the color, not the word" } },
      { id: "nBack", title: { el: "N-Back", en: "N-Back" }, icon: "🔙", desc: { el: "Θυμήσου N βήματα πίσω", en: "Remember N steps back" } },
      { id: "mentalRotation", title: { el: "Νοητική Περιστροφή", en: "Mental Rotation" }, icon: "🔄", desc: { el: "Βρες το ίδιο σχήμα", en: "Find the matching shape" } },
      { id: "attentionGrid", title: { el: "Πλέγμα Προσοχής", en: "Attention Grid" }, icon: "🔲", desc: { el: "Μέτρησε τα γράμματα", en: "Count the letters" } },
      { id: "chunking", title: { el: "Ομαδοποίηση Αριθμών", en: "Number Chunking" }, icon: "🔢", desc: { el: "Θυμήσου ακολουθίες αριθμών", en: "Remember number sequences" } },
      { id: "patternSpeed", title: { el: "Ταχύτητα Μοτίβων", en: "Pattern Speed" }, icon: "⚡", desc: { el: "Βρες γρήγορα το μοτίβο", en: "Find the pattern quickly" } },
      { id: "digitSpan", title: { el: "Εύρος Ψηφίων", en: "Digit Span" }, icon: "🔢", desc: { el: "Επανάλαβε τα ψηφία", en: "Repeat the digits" } },
      { id: "focusFilter", title: { el: "Φίλτρο Εστίασης", en: "Focus Filter" }, icon: "🎯", desc: { el: "Φιλτράρισε τα περιττά", en: "Filter distractors" } },
      { id: "colorSequence", title: { el: "Ακολουθία Χρωμάτων", en: "Color Sequence" }, icon: "🌈", desc: { el: "Θυμήσου τα χρώματα", en: "Remember the colors" } },
      { id: "numberBonds", title: { el: "Ζεύγη Αριθμών", en: "Number Bonds" }, icon: "🔗", desc: { el: "Βρες ζεύγη που αθροίζουν", en: "Find pairs that sum up" } },
      { id: "wordMemory", title: { el: "Μνήμη Λέξεων", en: "Word Memory" }, icon: "📝", desc: { el: "Θυμήσου τις λέξεις", en: "Remember the words" } },
      { id: "reactionChain", title: { el: "Αλυσίδα Αντίδρασης", en: "Reaction Chain" }, icon: "⚡", desc: { el: "Πάτα τους στόχους γρήγορα", en: "Tap targets quickly" } },
    ],
  },
  {
    id: "funGames",
    title: { el: "Διασκέδαση & Παιχνίδι", en: "Fun & Games" },
    desc: { el: "Λέξεις, γρίφοι εικόνων, trivia και πολλά ακόμα", en: "Words, picture puzzles, trivia and much more" },
    icon: "🎮",
    gradient: "from-amber-500 to-orange-600",
    subgroups: [
      { label: { el: "🔤 Λέξεις & Γλώσσα", en: "🔤 Words & Language" }, ids: ["wordScramble", "hangman", "wordSearch", "anagram", "chainWords", "synonymAntonym", "proverbs", "acronym"] },
      { label: { el: "🖼️ Εικόνες & Ήχοι", en: "🖼️ Images & Sounds" }, ids: ["emojiQuiz", "guessImage", "fourPics", "guessSound", "movieQuiz", "spotThePattern", "pictogram"] },
      { label: { el: "❓ Γνώσεις & Προκλήσεις", en: "❓ Knowledge & Challenges" }, ids: ["triviaQuiz", "trueOrFalse", "dailyChallenge", "riddles", "flagQuiz", "capitalCities", "numberCross"] },
    ],
    games: [
      { id: "wordScramble", title: { el: "Ανακάτεμα Λέξεων", en: "Word Scramble" }, icon: "🔤", desc: { el: "Βρες τη σωστή λέξη", en: "Find the right word" } },
      { id: "emojiQuiz", title: { el: "Emoji Quiz", en: "Emoji Quiz" }, icon: "😎", desc: { el: "Μάντεψε από emojis", en: "Guess from emojis" } },
      { id: "triviaQuiz", title: { el: "Trivia Quiz", en: "Trivia Quiz" }, icon: "❓", desc: { el: "Ερωτήσεις γνώσεων", en: "Knowledge questions" } },
      { id: "guessImage", title: { el: "Μάντεψε την Εικόνα", en: "Guess the Image" }, icon: "🖼️", desc: { el: "Εικόνα που ξεκαθαρίζει", en: "Image becomes clearer" } },
      { id: "hangman", title: { el: "Hangman", en: "Hangman" }, icon: "💀", desc: { el: "Κλασικό παιχνίδι λέξεων", en: "Classic word game" } },
      { id: "fourPics", title: { el: "4 Εικόνες 1 Λέξη", en: "4 Pics 1 Word" }, icon: "🖼️", desc: { el: "Βρες την κοινή λέξη", en: "Find the common word" } },
      { id: "guessSound", title: { el: "Guess the Sound", en: "Guess the Sound" }, icon: "🔊", desc: { el: "Μάντεψε τον ήχο", en: "Guess the sound" } },
      { id: "trueOrFalse", title: { el: "True or False", en: "True or False" }, icon: "✅", desc: { el: "Σωστό ή Λάθος", en: "True or False" } },
      { id: "dailyChallenge", title: { el: "Daily Challenge", en: "Daily Challenge" }, icon: "📅", desc: { el: "Ημερήσια πρόκληση", en: "Daily challenge" } },
      { id: "wordSearch", title: { el: "Word Search", en: "Word Search" }, icon: "🔎", desc: { el: "Βρες λέξεις στο πλέγμα", en: "Find words in grid" } },
      { id: "riddles", title: { el: "Γρίφοι", en: "Riddles" }, icon: "🤔", desc: { el: "Λύσε γρίφους λέξεων", en: "Solve word riddles" } },
      { id: "anagram", title: { el: "Αναγραμματισμοί", en: "Anagrams" }, icon: "🔤", desc: { el: "Βρες τη λέξη", en: "Find the anagram" } },
      { id: "flagQuiz", title: { el: "Σημαίες Χωρών", en: "Flag Quiz" }, icon: "🏳️", desc: { el: "Αναγνώρισε τη σημαία", en: "Recognize the flag" } },
      { id: "capitalCities", title: { el: "Πρωτεύουσες", en: "Capital Cities" }, icon: "🌍", desc: { el: "Βρες την πρωτεύουσα", en: "Find the capital" } },
      { id: "movieQuiz", title: { el: "Ταινίες Quiz", en: "Movie Quiz" }, icon: "🎬", desc: { el: "Μάντεψε την ταινία", en: "Guess the movie" } },
      { id: "synonymAntonym", title: { el: "Συνώνυμα & Αντίθετα", en: "Synonyms & Antonyms" }, icon: "📖", desc: { el: "Βρες συνώνυμα ή αντίθετα", en: "Find synonyms or antonyms" } },
      { id: "proverbs", title: { el: "Παροιμίες", en: "Proverbs" }, icon: "📜", desc: { el: "Ολοκλήρωσε την παροιμία", en: "Complete the proverb" } },
      { id: "spotThePattern", title: { el: "Μοτίβα", en: "Spot the Pattern" }, icon: "🔍", desc: { el: "Βρες τη συνέχεια", en: "Find what comes next" } },
      { id: "acronym", title: { el: "Ακρωνύμια", en: "Acronyms" }, icon: "🔡", desc: { el: "Τι σημαίνει το ακρωνύμιο;", en: "What does it stand for?" } },
      { id: "chainWords", title: { el: "Αλυσίδα Λέξεων", en: "Chain Words" }, icon: "🔗", desc: { el: "Τελευταίο γράμμα → πρώτο", en: "Last letter → first" } },
      { id: "numberCross", title: { el: "Αριθμητικός Γρίφος", en: "Number Cross" }, icon: "🔢", desc: { el: "Βρες τα σωστά ζεύγη", en: "Find the correct pairs" } },
      { id: "pictogram", title: { el: "Εικονόγραμμα", en: "Pictogram" }, icon: "🧮", desc: { el: "Λύσε εξισώσεις εικόνων", en: "Solve picture equations" } },
    ],
  },
  {
    id: "logicThinking",
    title: { el: "Λογική Σκέψη", en: "Logic Thinking" },
    desc: { el: "Sudoku, γρίφοι λογικής, πάζλ αριθμών και στρατηγική", en: "Sudoku, logic puzzles, number games and strategy" },
    icon: "🧩",
    gradient: "from-cyan-500 to-blue-600",
    subgroups: [
      { label: { el: "🔢 Αριθμοί & Πάζλ", en: "🔢 Numbers & Puzzles" }, ids: ["sudoku", "numberLogic", "mathPatterns", "matchstick", "kenKen", "nonogram", "binaryPuzzle", "cryptarithmetic"] },
      { label: { el: "🧠 Λογικοί Γρίφοι", en: "🧠 Logic Puzzles" }, ids: ["logicGrid", "whoTellsTruth", "riverCrossing", "syllogism", "balanceScale", "logicGates", "gridDeduction", "setPuzzle"] },
      { label: { el: "🗺️ Χωρικά & Στρατηγικής", en: "🗺️ Spatial & Strategy" }, ids: ["towersOfHanoi", "pathFinder", "lightUp", "masterMind", "mineSweep", "sequencePuzzle"] },
    ],
    games: [
      { id: "sudoku", title: { el: "Sudoku", en: "Sudoku" }, icon: "🔢", desc: { el: "Κλασικό puzzle αριθμών", en: "Classic number puzzle" } },
      { id: "logicGrid", title: { el: "Logic Grid Puzzle", en: "Logic Grid Puzzle" }, icon: "📊", desc: { el: "Λογικοί γρίφοι πίνακα", en: "Logic grid puzzles" } },
      { id: "riverCrossing", title: { el: "River Crossing", en: "River Crossing" }, icon: "🚣", desc: { el: "Μεταφορά με περιορισμούς", en: "Transport with constraints" } },
      { id: "matchstick", title: { el: "Matchstick Puzzle", en: "Matchstick Puzzle" }, icon: "🔥", desc: { el: "Διόρθωσε την εξίσωση", en: "Fix the equation" } },
      { id: "whoTellsTruth", title: { el: "Ποιος Λέει Αλήθεια", en: "Who Tells the Truth" }, icon: "🤥", desc: { el: "Βρες ποιος λέει αλήθεια", en: "Find who tells truth" } },
      { id: "mathPatterns", title: { el: "Μαθηματικά Patterns", en: "Math Patterns" }, icon: "📐", desc: { el: "Συμπλήρωσε το μοτίβο", en: "Complete the pattern" } },
      { id: "towersOfHanoi", title: { el: "Towers Puzzle", en: "Towers of Hanoi" }, icon: "🗼", desc: { el: "Μετακίνησε τους δίσκους", en: "Move the disks" } },
      { id: "pathFinder", title: { el: "Path Finder", en: "Path Finder" }, icon: "🧭", desc: { el: "Βρες τη διαδρομή", en: "Find the path" } },
      { id: "lightUp", title: { el: "Light Up Puzzle", en: "Light Up Puzzle" }, icon: "💡", desc: { el: "Άναψε όλα τα φώτα", en: "Light up all cells" } },
      { id: "numberLogic", title: { el: "Number Logic", en: "Number Logic" }, icon: "🧮", desc: { el: "Τοποθέτησε σωστά τους αριθμούς", en: "Place numbers correctly" } },
      { id: "nonogram", title: { el: "Nonogram", en: "Nonogram" }, icon: "🖼️", desc: { el: "Ζωγράφισε με αριθμούς", en: "Paint by numbers" } },
      { id: "kenKen", title: { el: "KenKen", en: "KenKen" }, icon: "🔢", desc: { el: "Μαθηματικό πάζλ", en: "Math puzzle grid" } },
      { id: "masterMind", title: { el: "Master Mind", en: "Master Mind" }, icon: "🎯", desc: { el: "Σπάσε τον κώδικα", en: "Break the code" } },
      { id: "syllogism", title: { el: "Συλλογισμοί", en: "Syllogisms" }, icon: "🧠", desc: { el: "Λογικοί συλλογισμοί", en: "Logical reasoning" } },
      { id: "balanceScale", title: { el: "Ζυγαριά", en: "Balance Scale" }, icon: "⚖️", desc: { el: "Βρες τα σωστά βάρη", en: "Find the correct weights" } },
      { id: "cryptarithmetic", title: { el: "Κρυπταριθμητική", en: "Cryptarithmetic" }, icon: "🔐", desc: { el: "Αντικατάστησε γράμματα με ψηφία", en: "Replace letters with digits" } },
      { id: "sequencePuzzle", title: { el: "Ακολουθίες", en: "Sequence Puzzle" }, icon: "🔢", desc: { el: "Βρες τον κανόνα", en: "Find the rule" } },
      { id: "mineSweep", title: { el: "Ναρκαλιευτής", en: "Mine Sweep" }, icon: "💣", desc: { el: "Αποφύγε τις νάρκες", en: "Avoid the mines" } },
      { id: "setPuzzle", title: { el: "Set Puzzle", en: "Set Puzzle" }, icon: "🃏", desc: { el: "Βρες τα σετ", en: "Find the sets" } },
      { id: "logicGates", title: { el: "Λογικές Πύλες", en: "Logic Gates" }, icon: "🔌", desc: { el: "AND, OR, NOT κυκλώματα", en: "AND, OR, NOT circuits" } },
      { id: "gridDeduction", title: { el: "Παζλ Συμπερασμού", en: "Grid Deduction" }, icon: "📋", desc: { el: "Λύσε με στοιχεία", en: "Solve with clues" } },
      { id: "binaryPuzzle", title: { el: "Binary Puzzle", en: "Binary Puzzle" }, icon: "0️⃣", desc: { el: "Πλέγμα 0 και 1", en: "Grid of 0s and 1s" } },
    ],
  },
];
