export const BOT_PERSONAS = [
  { id: "ninja",   name: { el: "Νίντζα Σκιά",       en: "Shadow Ninja" },   emoji: "🥷", speed: 0.7, accuracy: 0.85, color: "from-slate-700 to-slate-900" },
  { id: "wizard",  name: { el: "Σοφός Μάγος",        en: "Wise Wizard" },   emoji: "🧙", speed: 0.85, accuracy: 0.9,  color: "from-purple-500 to-indigo-600" },
  { id: "robot",   name: { el: "Ρομπότ X-9",          en: "Robot X-9" },     emoji: "🤖", speed: 0.5, accuracy: 0.8,  color: "from-cyan-500 to-blue-600" },
  { id: "dragon",  name: { el: "Δράκος Φωτιάς",      en: "Fire Dragon" },   emoji: "🐉", speed: 0.6, accuracy: 0.75, color: "from-red-500 to-orange-600" },
  { id: "fairy",   name: { el: "Νεράιδα Άστρι",      en: "Star Fairy" },    emoji: "🧚", speed: 0.9, accuracy: 0.7,  color: "from-pink-400 to-rose-500" },
  { id: "alien",   name: { el: "Εξωγήινος Ζορκ",     en: "Alien Zork" },    emoji: "👽", speed: 0.75, accuracy: 0.85, color: "from-green-500 to-emerald-600" },
  { id: "panda",   name: { el: "Πάντα Λιν",          en: "Panda Lin" },     emoji: "🐼", speed: 0.55, accuracy: 0.95, color: "from-slate-400 to-slate-600" },
  { id: "knight",  name: { el: "Ιππότης Άρθουρος",   en: "Knight Arthur" }, emoji: "⚔️", speed: 0.8, accuracy: 0.8,  color: "from-amber-500 to-yellow-600" },
  { id: "pirate",  name: { el: "Πειρατής Μπράντι",   en: "Pirate Brandi" }, emoji: "🏴‍☠️", speed: 0.65, accuracy: 0.7,  color: "from-slate-600 to-slate-800" },
];

export const BR_QUESTIONS = [
  { q: { el: "Πόσο είναι 7 × 8;", en: "What is 7 × 8?" }, opts: ["54", "56", "58", "63"], correct: 1 },
  { q: { el: "Ποια είναι η πρωτεύουσα της Γαλλίας;", en: "Capital of France?" }, opts: [{ el: "Λονδίνο", en: "London" }, { el: "Παρίσι", en: "Paris" }, { el: "Βερολίνο", en: "Berlin" }, { el: "Ρώμη", en: "Rome" }], correct: 1 },
  { q: { el: "100 - 47 = ?", en: "100 - 47 = ?" }, opts: ["43", "53", "57", "63"], correct: 1 },
  { q: { el: "Πόσοι μήνες έχει το έτος;", en: "How many months in a year?" }, opts: ["10", "11", "12", "13"], correct: 2 },
  { q: { el: "Ποιο πλανήτης είναι ο πιο μεγάλος;", en: "Largest planet?" }, opts: [{ el: "Άρης", en: "Mars" }, { el: "Δίας", en: "Jupiter" }, { el: "Κρόνος", en: "Saturn" }, { el: "Ποσειδώνας", en: "Neptune" }], correct: 1 },
  { q: { el: "9 × 9 = ?", en: "9 × 9 = ?" }, opts: ["72", "81", "89", "99"], correct: 1 },
  { q: { el: "Ποιο ζώο πετά;", en: "Which animal flies?" }, opts: [{ el: "Σκυλί", en: "Dog" }, { el: "Αετός", en: "Eagle" }, { el: "Ψάρι", en: "Fish" }, { el: "Κάβουρας", en: "Crab" }], correct: 1 },
  { q: { el: "12 + 28 = ?", en: "12 + 28 = ?" }, opts: ["38", "40", "42", "48"], correct: 1 },
  { q: { el: "Πόσες πλευρές έχει το τρίγωνο;", en: "Sides of a triangle?" }, opts: ["2", "3", "4", "5"], correct: 1 },
  { q: { el: "Ποιο χρώμα προκύπτει από κίτρινο + μπλε;", en: "Yellow + blue makes?" }, opts: [{ el: "Πράσινο", en: "Green" }, { el: "Πορτοκαλί", en: "Orange" }, { el: "Μωβ", en: "Purple" }, { el: "Καφέ", en: "Brown" }], correct: 0 },
  { q: { el: "144 ÷ 12 = ?", en: "144 ÷ 12 = ?" }, opts: ["10", "12", "14", "16"], correct: 1 },
  { q: { el: "Ποιος έγραψε την Ιλιάδα;", en: "Who wrote the Iliad?" }, opts: [{ el: "Πλάτων", en: "Plato" }, { el: "Όμηρος", en: "Homer" }, { el: "Σοφοκλής", en: "Sophocles" }, { el: "Σωκράτης", en: "Socrates" }], correct: 1 },
  { q: { el: "Πόσα δάχτυλα έχει ένα χέρι;", en: "Fingers in one hand?" }, opts: ["4", "5", "6", "10"], correct: 1 },
  { q: { el: "Ποιο είναι το αντίθετο του «μεγάλο»;", en: "Opposite of 'big'?" }, opts: [{ el: "Μικρό", en: "Small" }, { el: "Πλατύ", en: "Wide" }, { el: "Ψηλό", en: "Tall" }, { el: "Στενό", en: "Narrow" }], correct: 0 },
  { q: { el: "25 × 4 = ?", en: "25 × 4 = ?" }, opts: ["80", "90", "100", "125"], correct: 2 },
  { q: { el: "Πόσες ημέρες έχει ο Απρίλιος;", en: "Days in April?" }, opts: ["28", "29", "30", "31"], correct: 2 },
  { q: { el: "Ποια ήπειρος είναι η μεγαλύτερη;", en: "Largest continent?" }, opts: [{ el: "Αφρική", en: "Africa" }, { el: "Ασία", en: "Asia" }, { el: "Ευρώπη", en: "Europe" }, { el: "Αμερική", en: "America" }], correct: 1 },
  { q: { el: "60 ÷ 5 = ?", en: "60 ÷ 5 = ?" }, opts: ["10", "12", "14", "15"], correct: 1 },
  { q: { el: "Ποιο είναι το πιο γρήγορο ζώο;", en: "Fastest animal?" }, opts: [{ el: "Λύκος", en: "Wolf" }, { el: "Γεράκι", en: "Falcon" }, { el: "Άλογο", en: "Horse" }, { el: "Λιοντάρι", en: "Lion" }], correct: 1 },
  { q: { el: "8² = ?", en: "8² = ?" }, opts: ["16", "32", "64", "128"], correct: 2 },
];
