export const GAME_INSTRUCTIONS = {
  tapPuzzle:              { el: "Πάτα τα κομμάτια με τη σωστή σειρά για να φτιάξεις την εικόνα!", en: "Tap the pieces in the right order to build the picture!" },
  imagePuzzle:            { el: "Σύρε τα κομμάτια στις σωστές θέσεις!", en: "Drag the pieces to the correct positions!" },
  bubblePop:              { el: "Σκάσε τις φούσκες όσο πιο γρήγορα μπορείς!", en: "Pop the bubbles as fast as you can!" },
  shapeMatch:             { el: "Βάλε κάθε σχήμα στη σωστή θέση!", en: "Put each shape in the correct spot!" },
  colorMatch:             { el: "Βρες το σωστό χρώμα!", en: "Find the right color!" },
  animalSounds:           { el: "Άκουσε τον ήχο και βρες ποιο ζώο είναι!", en: "Listen to the sound and find the animal!" },
  countAndLearn:          { el: "Μέτρα τα αντικείμενα και διάλεξε τον αριθμό!", en: "Count the objects and choose the number!" },
  musicalPiano:           { el: "Παίξε μουσική στο πιάνο!", en: "Play music on the piano!" },
  emotionsMatch:          { el: "Ταίριαξε κάθε πρόσωπο με το σωστό συναίσθημα!", en: "Match each face with the right emotion!" },
  foodSorting:            { el: "Βάλε τα φαγητά στη σωστή κατηγορία!", en: "Put the food in the right category!" },
  memoryMatch:            { el: "Βρες τα ζευγάρια αναποδογυρίζοντας τις κάρτες!", en: "Find matching pairs by flipping cards!" },
  alphabetMatch:          { el: "Ταίριαξε κάθε γράμμα με τη σωστή εικόνα!", en: "Match each letter with the right image!" },
  animalHabitats:         { el: "Βάλε κάθε ζώο στο σπίτι του!", en: "Put each animal in its home!" },
  animalTracks:           { el: "Ταίριαξε κάθε ζώο με τα ίχνη του!", en: "Match each animal with its tracks!" },
  bodyParts:              { el: "Βρες τα μέρη του σώματος!", en: "Find the body parts!" },
  colorDrawing:           { el: "Ζωγράφισε με τα χρώματα!", en: "Draw with the colors!" },
  vehicleSounds:          { el: "Άκουσε τον ήχο και βρες το όχημα!", en: "Listen to the sound and find the vehicle!" },
  syllableListening:      { el: "Άκουσε τη συλλαβή και διάλεξε τη σωστή λέξη!", en: "Listen to the syllable and choose the right word!" },
  firstLetterGame:        { el: "Βρες το πρώτο γράμμα της λέξης!", en: "Find the first letter of the word!" },
  hiddenLetterGame:       { el: "Βρες το κρυφό γράμμα σε κάθε λέξη!", en: "Find the hidden letter in each word!" },
  rhymeListening:         { el: "Άκουσε και βρες ποια λέξη ομοιοκαταληκτεί!", en: "Listen and find the rhyming word!" },
  wakeUpLetterGame:       { el: "Βρες το γράμμα που λείπει!", en: "Find the missing letter!" },
  guessWhatGame:          { el: "Μάντεψε τι είναι από την περιγραφή!", en: "Guess what it is from the description!" },
  similarSoundsGame:      { el: "Βρες τις λέξεις με παρόμοιο ήχο!", en: "Find words with similar sounds!" },
  completeSentenceGame:   { el: "Ολοκλήρωσε τη φράση με τη σωστή λέξη!", en: "Complete the sentence with the right word!" },
  findOddOneOutGame:      { el: "Βρες ποιο δεν ταιριάζει!", en: "Find the one that doesn't belong!" },
  alphabetRoadGame:       { el: "Οδήγησε στα σωστά γράμματα!", en: "Drive to the correct letters!" },
  whichIsLessGame:        { el: "Ποια ομάδα έχει λιγότερα;", en: "Which group has fewer?" },
  findMissingNumberGame:  { el: "Βρες τον αριθμό που λείπει από τη σειρά!", en: "Find the missing number in the sequence!" },
  whatRemainsGame:        { el: "Αφαίρεσε και μέτρησε τι έμεινε!", en: "Subtract and count what remains!" },
  matchShapeObjectGame:   { el: "Ταίριαξε κάθε σχήμα με το αντικείμενο!", en: "Match each shape with the object!" },
  flippedShapesGame:      { el: "Βρες το σχήμα με τον σωστό προσανατολισμό!", en: "Find the shape with the correct orientation!" },
  sortBySizeGame:         { el: "Ταξινόμησε τα αντικείμενα από μικρό σε μεγάλο!", en: "Sort the objects from smallest to largest!" },
  groupByCategoriesGame:  { el: "Βάλε τα αντικείμενα στα σωστά καλάθια!", en: "Put the objects in the correct baskets!" },
  robotRequestsGame:      { el: "Δώσε στο ρομπότ αυτό που ζητάει!", en: "Give the robot what it asks for!" },
  patternRecognitionGame: { el: "Διάλεξε τη σωστή συνέχεια του μοτίβου!", en: "Choose the correct pattern continuation!" },
  brokenNumberGame:       { el: "Συνέθεσε τον αριθμό από τα κομμάτια!", en: "Assemble the number from the pieces!" },
  paintSameObjects:       { el: "Βάψε όλα τα αντικείμενα που είναι ίδια!", en: "Paint all the objects that are the same!" },
  mazeGame:               { el: "Σύρε τη μπάλα μέσα από τον λαβύρινθο!", en: "Drag the ball through the maze!" },
  findHalfShape:          { el: "Βρες το σωστό δεξί μισό του σχήματος!", en: "Find the correct right half of the shape!" },
  fixThePicture:          { el: "Βρες ποιο κομμάτι είναι λάθος και διόρθωσέ το!", en: "Find the wrong piece and fix it!" },
  drawTheShadow:          { el: "Ζωγράφισε τη σκιά του αντικειμένου!", en: "Draw the shadow of the object!" },
  createScene:            { el: "Σύρε τα αντικείμενα για να φτιάξεις τη σκηνή!", en: "Drag the objects to create the scene!" },
  stickerCard:            { el: "Βάλε τα stickers στις σωστές θέσεις!", en: "Place the stickers in the right spots!" },
  freezeMelt:             { el: "Λιώσε τα παγωμένα ζώα με τη φωτιά!", en: "Melt the frozen animals with fire!" },
  completeSymmetry:       { el: "Ζωγράφισε το δεξί μισό για να γίνει συμμετρικό!", en: "Draw the right half to make it symmetrical!" },
  whatWasInBetween:       { el: "Θυμήσου ποιο ήταν στη μέση!", en: "Remember which one was in the middle!" },
  flippedSoundCards:      { el: "Αναποδογύρισε τις κάρτες και βρες τα ζευγάρια ήχων!", en: "Flip the cards and find the sound pairs!" },
  movementSequence:       { el: "Θυμήσου τις κινήσεις και επανάλαβέ τες!", en: "Remember the movements and repeat them!" },
  guessFromPieces:        { el: "Κοίτα τα κομμάτια και μάντεψε τι είναι!", en: "Look at the pieces and guess what it is!" },
  quickTap:               { el: "Πάτα γρήγορα το σωστό αντικείμενο!", en: "Tap the correct object quickly!" },
  positionMemory:         { el: "Θυμήσου πού κρύφτηκε το αντικείμενο!", en: "Remember where the object was hidden!" },
  whichDisappeared:       { el: "Κοίτα προσεκτικά. Ποιο εξαφανίστηκε;", en: "Look carefully. Which one disappeared?" },
  whichMoved:             { el: "Ποιο αντικείμενο μετακινήθηκε;", en: "Which object has moved?" },
  whatHeardFirst:         { el: "Άκουσε τους ήχους. Ποιον άκουσες πρώτο;", en: "Listen to the sounds. Which did you hear first?" },
  combineTwoImages:       { el: "Συνδύασε τις δύο εικόνες. Τι δημιουργούν;", en: "Combine the two images. What do they create?" },
  howDoesItFeel:          { el: "Κοίτα τι συμβαίνει. Πώς νιώθει αυτό το παιδί;", en: "Look at what's happening. How does this child feel?" },
  doTheRightThing:        { el: "Διάλεξε τη σωστή ευγενική πράξη!", en: "Choose the correct polite action!" },
  whoWaitsInLine:         { el: "Ποιο παιδί περιμένει υπομονετικά στη σειρά;", en: "Which child is waiting patiently in line?" },
  helpYourFriend:         { el: "Ο φίλος σου χρειάζεται βοήθεια. Τι θα κάνεις;", en: "Your friend needs help. What will you do?" },
  guessEmotionFromVoice:  { el: "Άκουσε τη φωνή και μάντεψε το συναίσθημα!", en: "Listen to the voice and guess the emotion!" },
  whatDoesItEat:          { el: "Ταίριαξε κάθε ζώο με αυτό που τρώει!", en: "Match each animal with what it eats!" },
  nightOrDay:             { el: "Αυτό γίνεται τη μέρα ή τη νύχτα;", en: "Does this happen during day or night?" },
  sinkOrFloat:            { el: "Βουλιάζει ή επιπλέει στο νερό;", en: "Does it sink or float in water?" },
  sortBySeasons:          { el: "Σε ποια εποχή ανήκει αυτό;", en: "Which season does this belong to?" },
  whatMovesWithWheels:    { el: "Ποιο κινείται με ρόδες;", en: "Which one moves with wheels?" },
  miniPuzzleGame:         { el: "Σύρε τα κομμάτια στις σωστές θέσεις!", en: "Drag the pieces to the correct spots!" },
  driveTheCarGame:        { el: "Οδήγησε το αυτοκινητάκι μέσα από τον λαβύρινθο!", en: "Drive the car through the maze!" },
  readingGame:            { el: "Διάβασε την ιστορία και απάντησε στις ερωτήσεις!", en: "Read the story and answer the questions!" },
  spellingGame:           { el: "Γράψε τη σωστή λέξη!", en: "Spell the correct word!" },
  findTheMissingLetterGame:    { el: "Βρες το γράμμα που λείπει από τη λέξη!", en: "Find the missing letter in the word!" },
  findTheMissingLetterIGame:   { el: "Συμπλήρωσε τη λέξη με Ι, Η ή Υ!", en: "Complete the word with the right letter!" },
  findTheMissingLetterIIGame:  { el: "Συμπλήρωσε τη λέξη με ι, η ή υ!", en: "Complete the word with the right letter!" },
  timeClockGame:          { el: "Κοίτα το ρολόι και πες μας τι ώρα είναι!", en: "Look at the clock and tell us what time it is!" },
  moneyRecognitionGame:   { el: "Αναγνώρισε τα νομίσματα και χαρτονομίσματα!", en: "Recognize the coins and banknotes!" },
  simpleGeographyGame:    { el: "Μάθε πράγματα για τον κόσμο!", en: "Learn things about the world!" },
  scienceExperimentsGame: { el: "Κάνε μικρά πειράματα επιστήμης!", en: "Do simple science experiments!" },
  findTheSumGame:         { el: "Βρες το σωστό αποτέλεσμα της πρόσθεσης!", en: "Find the correct addition result!" },
  findTheSumPairGame:     { el: "Βρες τα ζευγάρια που κάνουν το σωστό άθροισμα!", en: "Find the pairs that make the correct sum!" },
  mathBattleGame:         { el: "Πολέμα τέρατα λύνοντας μαθηματικές πράξεις!", en: "Fight monsters by solving math problems!" },
  wordBuilderGame:        { el: "Φτιάξε λέξεις από τα τυχαία γράμματα!", en: "Build words from random letters!" },
  logicGridPuzzleGame:    { el: "Λύσε το λογικό γρίφο! Ποιος κάθεται πού;", en: "Solve the logic puzzle! Who sits where?" },
  geographyQuizGame:      { el: "Βρες τις χώρες, πρωτεύουσες και σημαίες!", en: "Find countries, capitals and flags!" },
  scienceLabGame:         { el: "Κάνε πειράματα επιλέγοντας τα σωστά υλικά!", en: "Do experiments by choosing the right materials!" },
  codeBreakerGame:        { el: "Αποκωδικοποίησε το κρυφό μήνυμα!", en: "Decode the secret message!" },
  numberAdventureGame:    { el: "Λύσε τις πράξεις για να προχωρήσεις στην περιπέτεια!", en: "Solve the math problems to advance on your adventure!" },
  findTheWordGame:        { el: "Κοίτα την εικόνα και βρες τη σωστή λέξη!", en: "Look at the picture and find the right word!" },
  simpleLogicPuzzleGame:  { el: "Σκέψου λογικά και βρες τη σωστή απάντηση!", en: "Think logically and find the right answer!" },
  colorShapeGame:         { el: "Βρες το σωστό σχήμα και χρώμα!", en: "Find the right shape and color!" },
  storyBuilderGame:       { el: "Συμπλήρωσε τα κενά στην ιστορία!", en: "Fill in the blanks in the story!" },
  timelineGame:           { el: "Βάλε τα ιστορικά γεγονότα σε χρονολογική σειρά!", en: "Put historical events in chronological order!" },
  spaceExplorerGame:      { el: "Απάντησε ερωτήσεις για τους πλανήτες και το ηλιακό σύστημα!", en: "Answer questions about planets and the solar system!" },
  mythologyQuizGame:      { el: "Δοκίμασε τις γνώσεις σου στην ελληνική μυθολογία!", en: "Test your Greek mythology knowledge!" },
  inventorQuizGame:       { el: "Ταίριαξε τις εφευρέσεις με τους εφευρέτες τους!", en: "Match inventions with their inventors!" },
  musicRhythmGame:        { el: "Θυμήσου τον ρυθμό και επανάλαβέ τον σωστά!", en: "Remember the rhythm and repeat it correctly!" },
  equationBalancerGame:   { el: "Βρες τον αριθμό που λείπει για να ισορροπήσεις την εξίσωση!", en: "Find the missing number to balance the equation!" },
  percentageCalcGame:     { el: "Υπολόγισε τα ποσοστά και διάλεξε τη σωστή απάντηση!", en: "Calculate the percentages and pick the correct answer!" },
  analogiesGame:          { el: "Συμπλήρωσε την αναλογία: Α προς Β όπως Γ προς ...;", en: "Complete the analogy: A is to B as C is to ...?" },
  sequenceDecoderGame:    { el: "Βρες τον κανόνα της ακολουθίας και διάλεξε τον επόμενο αριθμό!", en: "Find the sequence rule and pick the next number!" },
  debugTheCodeGame:       { el: "Βρες ποια γραμμή κώδικα έχει το σφάλμα!", en: "Find which line of code has the bug!" },

  // ─── Adult: Brain Training ──────────────────────────────────────
  memoryCards:            { el: "Αναποδογύρισε κάρτες και βρες τα ζευγάρια πριν τελειώσει ο χρόνος!", en: "Flip cards and find matching pairs before time runs out!" },
  rememberSequence:       { el: "Θυμήσου τη σειρά που εμφανίζονται τα αντικείμενα και τοποθέτησέ τα σωστά!", en: "Remember the order items appear and place them correctly!" },
  simon:                  { el: "Παρακολούθησε τη σειρά χρωμάτων και επανάλαβέ τη! Κάθε γύρο μεγαλώνει!", en: "Watch the color sequence and repeat it! It grows each round!" },
  findDifference:         { el: "Κοίτα τις δύο εικόνες και βρες όλες τις διαφορές!", en: "Look at both images and find all the differences!" },
  quickReaction:          { el: "Πάτα στον στόχο αμέσως μόλις εμφανιστεί — μετράει ο χρόνος αντίδρασης!", en: "Tap the target as soon as it appears — your reaction time is measured!" },
  visualMemory:           { el: "Θυμήσου ποια τετράγωνα φωτίστηκαν και πάτησέ τα στη σωστή σειρά!", en: "Remember which squares lit up and tap them in the right order!" },
  speedMath:              { el: "Λύσε αριθμητικές πράξεις όσο πιο γρήγορα μπορείς!", en: "Solve arithmetic problems as fast as you can!" },
  memoryPath:             { el: "Θυμήσου τη διαδρομή που εμφανίστηκε και ακολούθησέ τη!", en: "Remember the path shown and follow it!" },
  matchSymbols:           { el: "Ταίριαξε τα σύμβολα που εμφανίστηκαν από μνήμης!", en: "Match the symbols from memory!" },
  missingItem:            { el: "Κοίτα τα αντικείμενα, ένα εξαφανίζεται — βρες ποιο!", en: "Watch the items, one disappears — find which one!" },
  stroopTest:             { el: "Πάτα το ΧΡΩΜΑ του γράμματος, όχι τη λέξη! Μη μπερδευτείς!", en: "Tap the COLOR of the text, not the word! Don't get confused!" },
  nBack:                  { el: "Πάτα όταν το τρέχον στοιχείο ταιριάζει με αυτό N βήματα πίσω!", en: "Tap when the current item matches the one N steps back!" },
  mentalRotation:         { el: "Βρες ποιο σχήμα είναι το ίδιο, απλά περιστραμμένο!", en: "Find which shape is the same, just rotated!" },
  attentionGrid:          { el: "Μέτρα πόσες φορές εμφανίζεται ένα γράμμα στο πλέγμα!", en: "Count how many times a letter appears in the grid!" },
  chunking:               { el: "Θυμήσου μεγάλες ακολουθίες αριθμών χωρίζοντάς τες σε ομάδες!", en: "Remember long number sequences by chunking them into groups!" },
  patternSpeed:           { el: "Βρες γρήγορα ποιο μοτίβο ταιριάζει — ο χρόνος τρέχει!", en: "Quickly find the matching pattern — time is ticking!" },
  digitSpan:              { el: "Δες τα ψηφία και επανάλαβέ τα με τη σωστή σειρά!", en: "See the digits and repeat them in the correct order!" },
  focusFilter:            { el: "Πάτα μόνο τους σωστούς στόχους, αγνόησε τα περιττά!", en: "Tap only the correct targets, ignore distractors!" },
  colorSequence:          { el: "Θυμήσου τη σειρά χρωμάτων που εμφανίστηκαν και επανάλαβέ τη!", en: "Remember the color sequence shown and repeat it!" },
  numberBonds:            { el: "Βρες ζεύγη αριθμών που αθροίζουν στον στόχο!", en: "Find pairs of numbers that add up to the target!" },
  wordMemory:             { el: "Θυμήσου τις λέξεις και βρες ποιες είναι καινούργιες!", en: "Remember the words and find which ones are new!" },
  reactionChain:          { el: "Πάτα τους στόχους με τη σωστή σειρά αμέσως!", en: "Tap the targets in the correct order immediately!" },

  // ─── Adult: Fun Games ───────────────────────────────────────────
  wordScramble:           { el: "Τα γράμματα είναι ανακατεμένα — βρες τη σωστή λέξη!", en: "The letters are scrambled — find the correct word!" },
  emojiQuiz:              { el: "Μάντεψε τη λέξη ή φράση από τα emojis!", en: "Guess the word or phrase from the emojis!" },
  triviaQuiz:             { el: "Απάντησε σε ερωτήσεις γνώσεων — πόσες θα βρεις;", en: "Answer trivia questions — how many will you get?" },
  guessImage:             { el: "Η εικόνα ξεκαθαρίζει σιγά σιγά — μάντεψε τι είναι!", en: "The image clears up gradually — guess what it is!" },
  hangman:                { el: "Μάντεψε τη λέξη γράμμα-γράμμα πριν ολοκληρωθεί ο σκελετός!", en: "Guess the word letter by letter before the hangman is complete!" },
  fourPics:               { el: "Τέσσερις εικόνες, μια λέξη — ποια τις συνδέει;", en: "Four pictures, one word — what connects them?" },
  guessSound:             { el: "Άκουσε τον ήχο και μάντεψε τι είναι!", en: "Listen to the sound and guess what it is!" },
  trueOrFalse:            { el: "Διάβασε την πρόταση — Σωστό ή Λάθος;", en: "Read the statement — True or False?" },
  dailyChallenge:         { el: "Κάθε μέρα μια νέα πρόκληση — λύσε τη!", en: "A new challenge every day — solve it!" },
  wordSearch:             { el: "Βρες τις κρυμμένες λέξεις στο πλέγμα γραμμάτων!", en: "Find the hidden words in the letter grid!" },
  riddles:                { el: "Διάβασε τον γρίφο και βρες τη σωστή απάντηση!", en: "Read the riddle and find the correct answer!" },
  anagram:                { el: "Αναδιάταξε τα γράμματα για να φτιάξεις τη σωστή λέξη!", en: "Rearrange the letters to form the correct word!" },
  flagQuiz:               { el: "Κοίτα τη σημαία και βρες ποιας χώρας είναι!", en: "Look at the flag and find which country it belongs to!" },
  capitalCities:          { el: "Ποια είναι η πρωτεύουσα; Βρες τη σωστή απάντηση!", en: "What's the capital? Find the correct answer!" },
  movieQuiz:              { el: "Μάντεψε την ταινία από εικόνες, περιγραφές ή emojis!", en: "Guess the movie from images, descriptions, or emojis!" },
  synonymAntonym:         { el: "Βρες το συνώνυμο ή αντίθετο της λέξης!", en: "Find the synonym or antonym of the word!" },
  proverbs:               { el: "Ολοκλήρωσε την παροιμία — ποια είναι η σωστή κατάληξη;", en: "Complete the proverb — what's the correct ending?" },
  spotThePattern:         { el: "Κοίτα τη σειρά και βρες τι ακολουθεί!", en: "Look at the sequence and find what comes next!" },
  acronym:                { el: "Τι σημαίνει αυτό το ακρωνύμιο; Βρες τη σωστή απάντηση!", en: "What does this acronym stand for? Find the correct answer!" },
  chainWords:             { el: "Φτιάξε αλυσίδα — το τελευταίο γράμμα γίνεται πρώτο!", en: "Build a chain — the last letter becomes the first!" },
  numberCross:            { el: "Βρες τα σωστά ζεύγη αριθμών που ικανοποιούν τον κανόνα!", en: "Find the correct number pairs that satisfy the rule!" },
  pictogram:              { el: "Κάθε εικόνα αντιστοιχεί σε αριθμό — λύσε την εξίσωση!", en: "Each picture represents a number — solve the equation!" },

  // ─── Adult: Logic Thinking ──────────────────────────────────────
  sudoku:                 { el: "Συμπλήρωσε το πλέγμα 9×9 — κάθε σειρά, στήλη και 3×3 πρέπει να έχει 1-9!", en: "Fill the 9×9 grid — each row, column, and 3×3 box must have 1-9!" },
  logicGrid:              { el: "Χρησιμοποίησε τα στοιχεία για να λύσεις το λογικό πάζλ!", en: "Use the clues to solve the logic grid puzzle!" },
  riverCrossing:          { el: "Μεταφέρε τα πάντα στην άλλη πλευρά χωρίς να σπάσεις τους κανόνες!", en: "Transport everything across without breaking the rules!" },
  matchstick:             { el: "Μετακίνησε ένα σπίρτο για να κάνεις σωστή την εξίσωση!", en: "Move one matchstick to make the equation correct!" },
  whoTellsTruth:          { el: "Διάβασε τις δηλώσεις και βρες ποιος λέει αλήθεια!", en: "Read the statements and find who tells the truth!" },
  mathPatterns:           { el: "Βρες τον κανόνα του μοτίβου και συμπλήρωσε το κενό!", en: "Find the pattern rule and fill in the blank!" },
  towersOfHanoi:          { el: "Μετακίνησε τους δίσκους στον τρίτο πάσσαλο — ποτέ μεγαλύτερο πάνω σε μικρότερο!", en: "Move disks to the third peg — never place bigger on smaller!" },
  pathFinder:             { el: "Βρες τη σωστή διαδρομή στον λαβύρινθο!", en: "Find the correct path through the maze!" },
  lightUp:                { el: "Τοποθέτησε λαμπτήρες ώστε να φωτιστεί κάθε κελί!", en: "Place bulbs so every cell is lit up!" },
  numberLogic:            { el: "Τοποθέτησε αριθμούς ώστε να ικανοποιούνται οι συνθήκες!", en: "Place numbers so all conditions are satisfied!" },
  nonogram:               { el: "Χρωμάτισε τα σωστά κελιά ακολουθώντας τους αριθμούς στο πλάι!", en: "Color the correct cells following the numbers on the side!" },
  kenKen:                 { el: "Γέμισε το πλέγμα — κάθε γραμμή/στήλη μοναδικοί αριθμοί, κάθε ομάδα δίνει το αποτέλεσμα!", en: "Fill the grid — unique numbers per row/column, each cage gives the result!" },
  masterMind:             { el: "Μάντεψε τον μυστικό κώδικα χρωμάτων — χρησιμοποίησε τα hints!", en: "Guess the secret color code — use the hints!" },
  syllogism:              { el: "Διάβασε τις προτάσεις και βρες ποιο συμπέρασμα είναι σωστό!", en: "Read the premises and find which conclusion is correct!" },
  balanceScale:           { el: "Βρες τα σωστά βάρη ώστε η ζυγαριά να ισορροπήσει!", en: "Find the correct weights to balance the scale!" },
  cryptarithmetic:        { el: "Αντικατάστησε κάθε γράμμα με ψηφίο ώστε η πράξη να βγαίνει σωστά!", en: "Replace each letter with a digit so the equation works!" },
  sequencePuzzle:         { el: "Βρες τον κανόνα της ακολουθίας και διάλεξε τον επόμενο!", en: "Find the rule of the sequence and pick the next one!" },
  mineSweep:              { el: "Αποκάλυψε τα ασφαλή κελιά — οι αριθμοί δείχνουν γειτονικές νάρκες!", en: "Reveal safe cells — numbers show neighboring mines!" },
  setPuzzle:              { el: "Βρες σετ 3 καρτών με κοινά ή εντελώς διαφορετικά χαρακτηριστικά!", en: "Find sets of 3 cards with all same or all different features!" },
  logicGates:             { el: "Ρύθμισε τις εισόδους AND/OR/NOT ώστε η έξοδος να είναι σωστή!", en: "Set the AND/OR/NOT inputs so the output is correct!" },
  gridDeduction:          { el: "Χρησιμοποίησε τα στοιχεία και τον αποκλεισμό για να λύσεις το πάζλ!", en: "Use clues and elimination to solve the puzzle!" },
  binaryPuzzle:           { el: "Συμπλήρωσε το πλέγμα με 0 και 1 — κανόνες: max 2 συνεχόμενα, ίσα 0/1!", en: "Fill the grid with 0s and 1s — rules: max 2 in a row, equal 0s/1s!" },
};
